name: FakeOP
main: net.legitmine.FakeOP
version: 2.1
description: Granting of fake operator status to players, execute specified conditions upon fake operators attempting commands.
author: superkabii
commands:
   fakeop:
       description: Sets a player as a fake OP.
       usage: /<command> [Player]
       permission: fakeop.op
   fakedeop:
       description: Removes fake OP status from a player.
       usage: /<command> [Player]
       permission: fakeop.op
permissions:
   fakeop.op:
       description: Set fake operator status on a player.
       default: false